import type { Challenge } from "../types";

export const sampleChallenges: Challenge[] = [
  {
    id: "ch-1",
    clipId: "1",
    problemId: "1",
    language: "Python",
    codeBlock: [
      "def twoSum(nums, target):",
      "    seen = {}",
      "    for i, num in enumerate(nums):",
      "        complement = target - num",
      "        if complement in seen:",
      "            return [seen[complement], i]",
      "        seen[num] = i",
    ],
    blankLineIndex: 3,
    blankLineContent: "        complement = target - num",
    acceptedAnswers: [
      "complement = target - num",
      "comp = target - num",
      "diff = target - num",
    ],
    hint: "What value are we looking for in the hash map?",
    explanation:
      "We compute the complement (target - current number) so we can check if we've already seen a number that adds up to the target.",
    difficulty: "Easy",
    pauseTimestamp: 5,
    xpValue: 15,
    tags: ["Hash Table", "Two Pointers"],
  },
  {
    id: "ch-2",
    clipId: "2",
    problemId: "3",
    language: "Python",
    codeBlock: [
      "def lengthOfLongestSubstring(s):",
      "    char_set = set()",
      "    l = 0",
      "    res = 0",
      "    for r in range(len(s)):",
      "        while s[r] in char_set:",
      "            char_set.remove(s[l])",
      "            l += 1",
      "        char_set.add(s[r])",
      "        res = max(res, r - l + 1)",
      "    return res",
    ],
    blankLineIndex: 9,
    blankLineContent: "        res = max(res, r - l + 1)",
    acceptedAnswers: [
      "res = max(res, r - l + 1)",
      "result = max(result, r - l + 1)",
      "ans = max(ans, r - l + 1)",
    ],
    hint: "How do you track the longest window seen so far?",
    explanation:
      "At each step, the window size is r - l + 1. We keep a running max to track the longest valid substring.",
    difficulty: "Medium",
    pauseTimestamp: 6,
    xpValue: 20,
    tags: ["Sliding Window", "Hash Table"],
  },
  {
    id: "ch-3",
    clipId: "4",
    problemId: "20",
    language: "Python",
    codeBlock: [
      "def isValid(s):",
      '    stack = []',
      '    mapping = {")": "(", "]": "[", "}": "{"}',
      "    for char in s:",
      "        if char in mapping:",
      "            top = stack.pop() if stack else '#'",
      "            if mapping[char] != top:",
      "                return False",
      "        else:",
      "            stack.append(char)",
      "    return not stack",
    ],
    blankLineIndex: 5,
    blankLineContent: "            top = stack.pop() if stack else '#'",
    acceptedAnswers: [
      "top = stack.pop() if stack else '#'",
      "top = stack.pop() if stack else \"#\"",
      "top = stack[-1] if stack else '#'",
    ],
    hint: "What do we pop from the stack, and what if it's empty?",
    explanation:
      "We pop the top of the stack to compare with the current closing bracket. If the stack is empty, we use a dummy value that won't match.",
    difficulty: "Easy",
    pauseTimestamp: 5,
    xpValue: 15,
    tags: ["Stack", "String"],
  },
  {
    id: "ch-4",
    clipId: "5",
    problemId: "21",
    language: "Python",
    codeBlock: [
      "def mergeTwoLists(l1, l2):",
      "    dummy = ListNode()",
      "    curr = dummy",
      "    while l1 and l2:",
      "        if l1.val <= l2.val:",
      "            curr.next = l1",
      "            l1 = l1.next",
      "        else:",
      "            curr.next = l2",
      "            l2 = l2.next",
      "        curr = curr.next",
      "    curr.next = l1 or l2",
      "    return dummy.next",
    ],
    blankLineIndex: 11,
    blankLineContent: "    curr.next = l1 or l2",
    acceptedAnswers: [
      "curr.next = l1 or l2",
      "curr.next = l1 if l1 else l2",
      "curr.next = l2 if not l1 else l1",
    ],
    hint: "After the loop, one list might still have remaining nodes.",
    explanation:
      "When the while loop ends, one list is exhausted. We attach whichever list still has nodes remaining.",
    difficulty: "Easy",
    pauseTimestamp: 5,
    xpValue: 15,
    tags: ["Linked List"],
  },
  {
    id: "ch-5",
    clipId: "6",
    problemId: "146",
    language: "Python",
    codeBlock: [
      "class LRUCache:",
      "    def __init__(self, capacity):",
      "        self.cap = capacity",
      "        self.cache = {}",
      "        self.head = Node(0, 0)",
      "        self.tail = Node(0, 0)",
      "        self.head.next = self.tail",
      "        self.tail.prev = self.head",
      "",
      "    def get(self, key):",
      "        if key in self.cache:",
      "            self._remove(self.cache[key])",
      "            self._insert(self.cache[key])",
      "            return self.cache[key].val",
      "        return -1",
    ],
    blankLineIndex: 13,
    blankLineContent: "            return self.cache[key].val",
    acceptedAnswers: [
      "return self.cache[key].val",
      "return self.cache[key].value",
    ],
    hint: "After moving the node to the front, what do we return?",
    explanation:
      "We remove the node from its current position and re-insert at the front (most recently used), then return its value.",
    difficulty: "Medium",
    pauseTimestamp: 7,
    xpValue: 20,
    tags: ["Hash Table", "Design", "Linked List"],
  },
];

export function getChallengeForClip(clipId: string): Challenge | undefined {
  return sampleChallenges.find((c) => c.clipId === clipId);
}
